// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_tienda.Infrastructure.Data;

#nullable disable

namespace back_tienda.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125173352_UsePostgresEnums")]
    partial class UsePostgresEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back_tienda.Core.Entities.Categoria", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdTienda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdTienda", "NombreCategoria")
                        .IsUnique();

                    b.ToTable("categorias", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Compra", b =>
                {
                    b.Property<Guid>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_compra")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_documento")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_compra")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaLimiteEdicion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_limite_edicion");

                    b.Property<Guid?>("IdProveedor")
                        .HasColumnType("uuid")
                        .HasColumnName("id_proveedor");

                    b.Property<Guid>("IdTienda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<bool>("PuedeEditar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("puede_editar");

                    b.Property<decimal>("TotalCompra")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_compra");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdTienda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("compras", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.DetalleCompra", b =>
                {
                    b.Property<Guid>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_detalle_compra")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("IdCompra")
                        .HasColumnType("uuid")
                        .HasColumnName("id_compra");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalleCompra");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_compras", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.DetalleVenta", b =>
                {
                    b.Property<Guid>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_detalle_venta")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto");

                    b.Property<Guid>("IdVenta")
                        .HasColumnType("uuid")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalleVenta");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("detalle_ventas", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Devolucion", b =>
                {
                    b.Property<Guid>("IdDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_devolucion")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_devolucion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<Guid>("IdVenta")
                        .HasColumnType("uuid")
                        .HasColumnName("id_venta");

                    b.Property<decimal?>("MontoDevuelto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_devuelto");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<Guid>("ProductoIdProducto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioIdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaIdVenta")
                        .HasColumnType("uuid");

                    b.HasKey("IdDevolucion");

                    b.HasIndex("ProductoIdProducto");

                    b.HasIndex("UsuarioIdUsuario");

                    b.HasIndex("VentaIdVenta");

                    b.ToTable("devoluciones", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.EmpleadoTienda", b =>
                {
                    b.Property<Guid>("IdEmpleadoTienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_empleado_tienda")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdEmpleado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empleado");

                    b.Property<Guid>("IdTienda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda");

                    b.Property<bool>("PuedeGestionarInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("puede_gestionar_inventario");

                    b.Property<bool>("PuedeRegistrarCompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("puede_registrar_compras");

                    b.Property<bool>("PuedeRegistrarVentas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("puede_registrar_ventas");

                    b.Property<bool>("PuedeVerReportes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("puede_ver_reportes");

                    b.HasKey("IdEmpleadoTienda");

                    b.HasIndex("IdTienda");

                    b.HasIndex("IdEmpleado", "IdTienda")
                        .IsUnique();

                    b.ToTable("empleados_tiendas", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Merma", b =>
                {
                    b.Property<Guid>("IdMerma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_merma")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaMerma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_merma")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto");

                    b.Property<Guid>("IdTienda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("ProductoIdProducto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TiendaIdTienda")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioIdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("IdMerma");

                    b.HasIndex("ProductoIdProducto");

                    b.HasIndex("TiendaIdTienda");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("mermas", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Producto", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CodigoProducto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_producto");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_ultima_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("IdCategoria")
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria");

                    b.Property<Guid>("IdTienda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal?>("PrecioCompra")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_venta");

                    b.Property<int>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_actual");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("UNIDAD")
                        .HasColumnName("unidad_medida");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdTienda", "CodigoProducto")
                        .IsUnique();

                    b.ToTable("productos", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_proveedor")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdTienda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda");

                    b.Property<string>("Nit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nit");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_proveedor");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdTienda", "NombreProveedor")
                        .IsUnique();

                    b.ToTable("proveedores", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Tienda", b =>
                {
                    b.Property<Guid>("IdTienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CorreoTienda")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo_tienda");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_ultima_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdDueño")
                        .HasColumnType("uuid")
                        .HasColumnName("id_dueño");

                    b.Property<string>("Nit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nit");

                    b.Property<string>("NombreTienda")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_tienda");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdTienda");

                    b.HasIndex("IdDueño");

                    b.ToTable("tiendas", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contraseña_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_ultima_modificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<int>("Rol")
                        .HasColumnType("tipo_rol")
                        .HasColumnName("rol");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("UsuarioNombre")
                        .IsUnique();

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Venta", b =>
                {
                    b.Property<Guid>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_venta")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_documento")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdTienda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tienda");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("TotalVenta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_venta");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdTienda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ventas", "public");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Categoria", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Tienda", "Tienda")
                        .WithMany("Categorias")
                        .HasForeignKey("IdTienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Compra", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("back_tienda.Core.Entities.Tienda", "Tienda")
                        .WithMany("Compras")
                        .HasForeignKey("IdTienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Tienda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.DetalleCompra", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Compra", "Compra")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Producto", "Producto")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.DetalleVenta", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Producto", "Producto")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Devolucion", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaIdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.EmpleadoTienda", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Usuario", "Empleado")
                        .WithMany("EmpleadoTiendas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Tienda", "Tienda")
                        .WithMany()
                        .HasForeignKey("IdTienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Merma", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Tienda", "Tienda")
                        .WithMany()
                        .HasForeignKey("TiendaIdTienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Tienda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Producto", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("back_tienda.Core.Entities.Tienda", "Tienda")
                        .WithMany("Productos")
                        .HasForeignKey("IdTienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Proveedor", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Tienda", "Tienda")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdTienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Tienda", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Usuario", "Dueño")
                        .WithMany("TiendasComoDueño")
                        .HasForeignKey("IdDueño")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dueño");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Venta", b =>
                {
                    b.HasOne("back_tienda.Core.Entities.Tienda", "Tienda")
                        .WithMany("Ventas")
                        .HasForeignKey("IdTienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_tienda.Core.Entities.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tienda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Compra", b =>
                {
                    b.Navigation("DetalleCompras");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Producto", b =>
                {
                    b.Navigation("DetalleCompras");

                    b.Navigation("DetalleVentas");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Tienda", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Compras");

                    b.Navigation("Productos");

                    b.Navigation("Proveedores");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("EmpleadoTiendas");

                    b.Navigation("TiendasComoDueño");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("back_tienda.Core.Entities.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
